# docker-compose.yml
version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_db_facial
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=reconocimiento_facial_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: