services:
  - type: web
    name: facerecon-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: facerecon-db
          property: connectionString
      - key: FACE_RECOGNITION_THRESHOLD
        value: 4000
      - key: ALERT_ENABLED
        value: true
    disk:
      name: facerecon-images
      mountPath: /opt/render/project/src/static/fotos_perfil
      sizeGB: 1

databases:
  - name: facerecon-db
    databaseName: facerecon
    user: facerecon_user
    plan: starter 