services:
  - type: web
    name: facerecon-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://villitaqt:VIwhRET7lfwuyggiYPU7KERwqorA1ndH@dpg-d1cpf86r433s7384v5hg-a.oregon-postgres.render.com/face_recon_db
      - key: FACE_RECOGNITION_THRESHOLD
        value: 4000
      - key: ALERT_ENABLED
        value: true
    disk:
      name: facerecon-images
      mountPath: /opt/render/project/src/static/fotos_perfil
      sizeGB: 1