services:
  - type: web
    name: facerecon-api
    env: docker
    image: tu_usuario_dockerhub/facerecon-api:latest
    port: 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: facerecon-db
          property: connectionString
      - key: FACE_RECOGNITION_THRESHOLD
        value: 4000
      - key: ALERT_ENABLED
        value: true
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: facerecon-images
      mountPath: /app/static/fotos_perfil
      sizeGB: 1

databases:
  - name: facerecon-db
    databaseName: facerecon
    user: facerecon
    plan: free